# fly.toml file generated for codeday-showcase-gql on 2023-05-24T09:53:21-07:00

app = "codeday-showcase-gql"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "sea"

[experimental]
  auto_rollback = true
